# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e1483d1e4c943f6cb70d93b042e4865b"
name = "whishlist-creator"
handle = "whishlist-creator"
application_url = "https://prominent-neighborhood-stickers-reply.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "elysium-homedecor.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_draft_orders,write_products"

[auth]
redirect_urls = [
  "https://prominent-neighborhood-stickers-reply.trycloudflare.com/auth/callback",
  "https://prominent-neighborhood-stickers-reply.trycloudflare.com/auth/shopify/callback",
  "https://prominent-neighborhood-stickers-reply.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
